apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: firebase-web-app-dev
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/dev-demo-project-366116/firebase-web-app/firebase-web-app@sha256:eb83eb3657e3fde248f265a3429223e4b55440e39fc736f7baf62d1b52603190
        ports:
        - containerPort: 8080
        env: 
        - name: "FIREBASE_API_KEY"
          value: "\"AIzaSyCWluCW71rZF56veVt-uz3j9rUH0yZorxU\""
        - name: "FIREBASE_AUTH_DOMAIN"
          value: "\"jlaude-labs-dev.firebaseapp.com\""
        - name: "FIREBASE_PROJECT_ID"
          value: "\"jlaude-labs-dev\""
        - name: "FIREBASE_STORAGE_BUCKET"
          value: "\"jlaude-labs-dev.appspot.com\""
        - name: "FIREBASE_MESSAGING_SENDER_ID"
          value: "\"302884190983\""
        - name: "FIREBASE_APPID"
          value: "\"1:302884190983:web:97023b3d94d216bd2263a2\""
        - name: "FIREBASE_MEASUREMENT_ID"
          value: "\"G-86B7N73E0Z\""
        - name: "GOOGLE_OAUTH_CLIENT_ID"
          value: "\"302884190983-t3b8rj7q5qqvvtecm564a8om3ak7j11m.apps.googleusercontent.com\""