apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: firebase-web-app
profiles:
- name: dev
  manifests:
    rawYaml:
    - firebase-web-app-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - firebase-web-app-prod.yaml
deploy:
  cloudrun: {}
verify:
- name: verify-endpoint-test
  container:
    name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "wget $CLOUD_RUN_SERVICE_URLS"]
